@ECHO OFF
SETLOCAL

SET SCRIPTDESTINATION=%~1
SET DRIVERSROOT=%~2
SET NAME=%~3
SET SOURCEZIP=%~4

SET DRIVERSDEST=%DRIVERSROOT%\%NAME%
SET DRIVERSMOUNTPATH=\Drivers\%NAME%

7z x "%SOURCEZIP%" -o%DRIVERSDEST%
ECHO dism /Add-Driver /Image:W:\ /Driver:%DRIVERSMOUNTPATH% /Recurse > %SCRIPTDESTINATION%\%NAME%.bat
