Import-Module $PSScriptRoot\WinPE.psd1 -Force

(Get-ConsumerIsoPath)
(Get-BusinessIsoPath)
(Get-ServerIsoPath)
(Get-CumulativeUpdatePathFe)
(Get-CumulativeUpdatePathNi)
(Get-SurfaceBook2Drivers)
(Get-SurfaceBook3Drivers)
(Get-SurfaceGo2Drivers)
(Get-SurfaceGo3Drivers)
(Get-SurfaceLaptop2Drivers)
(Get-SurfaceLaptop3IntelDrivers)
(Get-SurfaceLaptop3AmdDrivers)
(Get-SurfaceLaptop4IntelDrivers)
(Get-SurfaceLaptop4AmdDrivers)
(Get-SurfaceLaptop5Drivers)
(Get-SurfaceLaptopGoDrivers)
(Get-SurfaceLaptopGo2Drivers)
(Get-SurfaceLaptopStudioDrivers)
(Get-SurfacePro6Drivers)
(Get-SurfacePro7Drivers)
(Get-SurfacePro7PlusDrivers)
(Get-SurfacePro8Drivers)
(Get-SurfacePro9Drivers)
(Get-SurfaceStudio2Drivers)
(Get-SurfaceStudio2PlusDrivers)
(Get-IntelRapidStorageDrivers)